# Generated by Django 3.2.7 on 2022-01-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='instruments',
            field=models.ManyToManyField(to='main.Instruments'),
        ),
        migrations.CreateModel(
            name='BandVacanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.band')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.instruments')),
                ('person', models.ManyToManyField(to='main.User')),
            ],
        ),
    ]
