# Generated by Django 3.2.7 on 2022-01-17 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20220117_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandvacanction',
            name='person',
        ),
        migrations.AddField(
            model_name='bandvacanction',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
