# Generated by Django 4.0 on 2022-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bandvacanction_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='band',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на чат'),
        ),
    ]
